In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [25]:
from utils import evaluate_classifier

In [26]:
from lightgbm import LGBMClassifier

In [23]:
results = pd.DataFrame()

In [24]:
results = evaluate_classifier('Raw', LGBMClassifier(is_unbalance=True), 
                              results, 'default')

Test fold: CTNNB1.csv
Train fold: Erk.csv
Train fold: Ikk2.csv
Train fold: IRF4.csv
Train fold: Jnk.csv
Train fold: LEF1.csv
Train fold: MYC.csv
Evaluating...
Confusion matrix:
[[56372 25606]
 [   35    25]]
            Model    Fold   ROC-AUC    G-mean  F1-Score  Accuracy  Precision  \
0  LGBMClassifier  CTNNB1  0.568392  0.535276  0.001946   0.68745   0.000975   

     Recall   Logloss Description  
0  0.416667  0.495957     default  
Test fold: Erk.csv
Train fold: CTNNB1.csv
Train fold: Ikk2.csv
Train fold: IRF4.csv
Train fold: Jnk.csv
Train fold: LEF1.csv
Train fold: MYC.csv
Evaluating...
Confusion matrix:
[[102300  38166]
 [   144    120]]
            Model Fold   ROC-AUC    G-mean  F1-Score  Accuracy  Precision  \
0  LGBMClassifier  Erk  0.626002  0.575362  0.006226  0.727777   0.003134   

     Recall   Logloss Description  
0  0.454545  0.480927     default  
Test fold: Ikk2.csv
Train fold: CTNNB1.csv
Train fold: Erk.csv
Train fold: IRF4.csv
Train fold: Jnk.csv
Train fold: LEF1

In [27]:
results

Model    Fold   ROC-AUC    G-mean  F1-Score  Accuracy  Precision  \
0  LGBMClassifier  CTNNB1  0.568392  0.535276  0.001946  0.687450   0.000975   
1  LGBMClassifier     Erk  0.626002  0.575362  0.006226  0.727777   0.003134   
2  LGBMClassifier    Ikk2  0.586635  0.132975  0.030128  0.952149   0.097708   
3  LGBMClassifier    IRF4  0.535977  0.508405  0.001411  0.487440   0.000706   
4  LGBMClassifier     Jnk  0.619648  0.275247  0.067921  0.927490   0.059463   
5  LGBMClassifier    LEF1  0.631975  0.595617  0.005548  0.557632   0.002786   
6  LGBMClassifier     MYC  0.669603  0.023150  0.001071  0.912581   1.000000   

     Recall   Logloss Description  
0  0.416667  0.495957     default  
1  0.454545  0.480927     default  
2  0.017810  0.192323     default  
3  0.530303  0.709721     default  
4  0.079184  0.224323     default  
5  0.636364  0.726999     default  
6  0.000536  0.286691     default

In [31]:
from utils import load_fold
from utils import train_model
from utils import evaluate_metrics

In [29]:
train, test, test_fold = load_fold('Raw', 0)

Test fold: CTNNB1.csv
Train fold: Erk.csv
Train fold: Ikk2.csv
Train fold: IRF4.csv
Train fold: Jnk.csv
Train fold: LEF1.csv
Train fold: MYC.csv


In [30]:
model, y_pred, y_pred_proba = train_model(LGBMClassifier(is_unbalance=True), train, test)

In [33]:
evaluate_metrics(test['Target'], y_pred, y_pred_proba)

Confusion matrix:
[[56372 25606]
 [   35    25]]
  Model Fold   ROC-AUC    G-mean  F1-Score  Accuracy  Precision    Recall  \
0             0.568392  0.535276  0.001946   0.68745   0.000975  0.416667   

    Logloss Description  
0  0.495957              


Model Fold   ROC-AUC    G-mean  F1-Score  Accuracy  Precision    Recall  \
0             0.568392  0.535276  0.001946   0.68745   0.000975  0.416667   

    Logloss Description  
0  0.495957

In [34]:
from catboost import CatBoostClassifier

In [ ]:
model, y_pred, y_pred_proba = train_model(CatBoostClassifier(), train, test)

In [36]:
evaluate_metrics(test['Target'], y_pred, y_pred_proba)

/home/robert/anaconda3/envs/kaggle/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/robert/anaconda3/envs/kaggle/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


Confusion matrix:
[[81978     0]
 [   60     0]]
  Model Fold   ROC-AUC  G-mean  F1-Score  Accuracy  Precision  Recall  \
0             0.632138     0.0       0.0  0.999269        0.0     0.0   

   Logloss Description  
0  0.02152              


Model Fold   ROC-AUC  G-mean  F1-Score  Accuracy  Precision  Recall  \
0             0.632138     0.0       0.0  0.999269        0.0     0.0   

   Logloss Description  
0  0.02152

In [56]:
model, y_pred, y_pred_proba = train_model(CatBoostClassifier(iterations=200, class_weights=[1,38]), train, test)

0:	learn: 0.6838196	total: 668ms	remaining: 2m 12s
1:	learn: 0.6771411	total: 1.35s	remaining: 2m 13s
2:	learn: 0.6771405	total: 1.79s	remaining: 1m 57s
3:	learn: 0.6771400	total: 2.23s	remaining: 1m 49s
4:	learn: 0.6699238	total: 2.91s	remaining: 1m 53s
5:	learn: 0.6638142	total: 3.62s	remaining: 1m 57s
6:	learn: 0.6638112	total: 4.06s	remaining: 1m 51s
7:	learn: 0.6638092	total: 4.51s	remaining: 1m 48s
8:	learn: 0.6638075	total: 4.94s	remaining: 1m 44s
9:	learn: 0.6638050	total: 5.36s	remaining: 1m 41s
10:	learn: 0.6638034	total: 5.8s	remaining: 1m 39s
11:	learn: 0.6638015	total: 6.32s	remaining: 1m 39s
12:	learn: 0.6638000	total: 6.78s	remaining: 1m 37s
13:	learn: 0.6637988	total: 7.19s	remaining: 1m 35s
14:	learn: 0.6637967	total: 7.65s	remaining: 1m 34s
15:	learn: 0.6637954	total: 8.15s	remaining: 1m 33s
16:	learn: 0.6637939	total: 8.63s	remaining: 1m 32s
17:	learn: 0.6637929	total: 9.06s	remaining: 1m 31s
18:	learn: 0.6637919	total: 9.49s	remaining: 1m 30s
19:	learn: 0.6637910	to

160:	learn: 0.6522012	total: 1m 12s	remaining: 17.5s
161:	learn: 0.6522012	total: 1m 12s	remaining: 17s
162:	learn: 0.6522012	total: 1m 12s	remaining: 16.6s
163:	learn: 0.6522011	total: 1m 13s	remaining: 16.1s
164:	learn: 0.6522010	total: 1m 13s	remaining: 15.7s
165:	learn: 0.6522008	total: 1m 14s	remaining: 15.2s
166:	learn: 0.6522008	total: 1m 14s	remaining: 14.8s
167:	learn: 0.6522006	total: 1m 15s	remaining: 14.3s
168:	learn: 0.6522005	total: 1m 15s	remaining: 13.9s
169:	learn: 0.6522004	total: 1m 15s	remaining: 13.4s
170:	learn: 0.6522004	total: 1m 16s	remaining: 12.9s
171:	learn: 0.6522003	total: 1m 16s	remaining: 12.5s
172:	learn: 0.6522001	total: 1m 17s	remaining: 12s
173:	learn: 0.6522001	total: 1m 17s	remaining: 11.6s
174:	learn: 0.6522001	total: 1m 18s	remaining: 11.1s
175:	learn: 0.6522001	total: 1m 18s	remaining: 10.7s
176:	learn: 0.6522001	total: 1m 18s	remaining: 10.2s
177:	learn: 0.6522001	total: 1m 19s	remaining: 9.8s
178:	learn: 0.6522001	total: 1m 19s	remaining: 9.35

In [57]:
# class_weights=[1,38]
evaluate_metrics(test['Target'], y_pred, y_pred_proba)

Confusion matrix:
[[66297 15681]
 [   49    11]]
  Model Fold  ROC-AUC    G-mean  F1-Score  Accuracy  Precision    Recall  \
0             0.49691  0.385052  0.001397   0.80826   0.000701  0.183333   

    Logloss Description  
0  0.648988              


Model Fold  ROC-AUC    G-mean  F1-Score  Accuracy  Precision    Recall  \
0             0.49691  0.385052  0.001397   0.80826   0.000701  0.183333   

    Logloss Description  
0  0.648988

In [55]:
# class_weights=[1,37]
evaluate_metrics(test['Target'], y_pred, y_pred_proba)

Confusion matrix:
[[45598 36380]
 [   35    25]]
  Model Fold   ROC-AUC    G-mean  F1-Score  Accuracy  Precision    Recall  \
0             0.504349  0.481414  0.001371   0.55612   0.000687  0.416667   

    Logloss Description  
0  0.657391              


Model Fold   ROC-AUC    G-mean  F1-Score  Accuracy  Precision    Recall  \
0             0.504349  0.481414  0.001371   0.55612   0.000687  0.416667   

    Logloss Description  
0  0.657391

In [53]:
# class_weights=[1,40]
evaluate_metrics(test['Target'], y_pred, y_pred_proba)

Confusion matrix:
[[ 2546 79432]
 [    1    59]]
  Model Fold   ROC-AUC    G-mean  F1-Score  Accuracy  Precision    Recall  \
0             0.517741  0.174756  0.001483  0.031754   0.000742  0.983333   

    Logloss Description  
0  0.714721              


Model Fold   ROC-AUC    G-mean  F1-Score  Accuracy  Precision    Recall  \
0             0.517741  0.174756  0.001483  0.031754   0.000742  0.983333   

    Logloss Description  
0  0.714721